services:
  - type: web
    name: ayurkisan-backend
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: SERVER_PORT
        value: "9090"
