# ===============================
# BASIC APPLICATION SETTINGS
# ===============================
spring.application.name=Ayurkisan-Ecommerce
server.port=9090

# ===============================
# MONGODB ATLAS
# ===============================
spring.data.mongodb.uri=${MONGO_URI}

# ===============================
# LOGGING (KEEP TERMINAL CLEAN)
# ===============================
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.mongodb=ERROR
logging.level.com.mongodb=ERROR

# Show only startup message
spring.main.banner-mode=off
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===============================
# EMAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
